sudo: required
language: python
python: "3.5"
services:
  - docker

env:
  global:
    - REPO=crops/extsdk-container
    - secure: "S70a+YTkxgG8U2tckSybEcQvHGx7yJGwvSG2xaLtYRdUm/+uN2estBG+qidaH3jaOYyt3vEIP7ih26i1TWjs0h7prMx0SKaEEGqBW3efc3rfi+jWaRWE/nuxgE/u0kxF+P242ngzIjaPMSbQIwvCZYeKMwFe916igA7DQTYPEkUlBMURPtjPy2z46LJHn/yEc6m5ELUvvZ92x+ajST73K0xT4Gi5jVR7RYVYtfZg7iT2Bq/0wlitEtY7GogKkiCKsxy+ym+iAw2YRpVTUxclCfD1F2n8FCvUeSFR2d1hXE0DDH9MvKabacVT22b95rbAQPYOWCOh7ymJe3hrrTMa2NtsTtcsY0uUaPaRBgm32/yjbDzFljQ9tSp1K4nnrCoBRBBOcGm/keKSQW+Y0AJ9cIVMaWRjHy8SPMmQZdPQSxl0T8vMC8pYSlvYcGgE3VLBfIpKaq1q+6Y/ZpWSVZhLU4/JK+hhhWlYYCJiVxa+hBHKuLRMh9EhemLTd99MOlaWO4GjdGwZMgXxktAnCgYZqM7ILw+HKrDsoJHU+NK9MnGUgYdltyauh2H61/JCv7ps9gwzr51CxP2cVLnPkvinWlKvEQka6NR3a2JZwHi8cu4vhGPv+vxfipiruqqPPx0t5XwL/I6ykbuKy/DYvUtaDJAeItUtHHRFhGaK7ANK23E="
    - secure: "Zq4GyvlMs/uFBMXJTDyOTbBTGIu2Ku7mdBp8CE1kfZKQxJ+5lwQhqpgn4j5KpLgAlgJJQUu9Pbm2wEkyanQTxCVGBuaZBoTfkhwMAoWyEdzBlX4IukqgUAwhc5RzP+xaFmORBHxxcbI63jDu5xAd3i1z0J8tgSwo4VBatF4qyiMdRwEIw70ZKymwUQqr2gBGAcBtJ8Ta3DlXb6fxmS1HcHkP5fVQCgFgt1c1CJUw1A3wxNK06bHmI6L3YhBf5f6T1jvlcXZAW1qZQjoI0BDlhx68L9hCndhjtphMMl8HrMzfc7UNe0V+nHTd4SEZ401f/d3d6PXb4AZPu4GPolIZkENtedkcsC+ywCX0CjYmBu842tMn7wE8nlHOgS6hNyHDdBvss2Si9d882hkKrHWZRyBUyPq/eJUFzHsGlHY8Nz2xxV6UaTEQe8Rn0rIhk3kLOfvX0ArxTQ7NJ0ZMK8Ube1PJGKscQ+gIYP4dTSFrJbuZN0t8871aagy/paU38GsKqEcm+/XWjILGeqzR3ijxqnX8SbbBkVMG4id/ygb26KnnAH1Mh/P8apzbvmIakm2tb881bhLtP+Krup4oxEh/J1Vwlxai8CxjWozQihiQoyr3zDucQQoOsQ/9zkGJIPHiX+VIB1SspK4vpXn+3IUDbXPJEJIytAAvx0cqZddgMdU="

before_install:
  - pip install pytest

script:
  - docker build -t ${REPO} .
  - pytest --testimage=${REPO}

after_success:
  - bash deploy.sh
